In [1]:
my_list = [1, 2, 3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
print(arr)

[1 2 3]


In [6]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
print(np.array(my_mat))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [16]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [101]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(4)

array([0.55475823, 0.76431897, 0.02641507, 0.3286238 ])

In [20]:
np.random.rand(4,4,4)

array([[[0.67552967, 0.38193395, 0.25805068, 0.60097769],
        [0.31172134, 0.12217516, 0.48596649, 0.10404213],
        [0.58410154, 0.45124303, 0.56263817, 0.893459  ],
        [0.18329485, 0.0985417 , 0.08452923, 0.95070378]],

       [[0.07227772, 0.18708486, 0.27290662, 0.75657088],
        [0.95075475, 0.49933051, 0.76728155, 0.11332141],
        [0.22746859, 0.71827814, 0.96795445, 0.03255769],
        [0.00824989, 0.27749474, 0.400817  , 0.47054435]],

       [[0.34157386, 0.79499801, 0.4851879 , 0.29800522],
        [0.10364004, 0.82110902, 0.94199475, 0.45156829],
        [0.96940577, 0.93308606, 0.77240148, 0.36757894],
        [0.97732883, 0.02471438, 0.97492776, 0.17323595]],

       [[0.28573846, 0.64465148, 0.62839415, 0.88988582],
        [0.31001316, 0.48652666, 0.82938096, 0.89164462],
        [0.81505697, 0.0060855 , 0.83797297, 0.29619017],
        [0.31875022, 0.98957565, 0.58234266, 0.77984439]]])

In [102]:
np.random.randn(2,2)

array([[-0.43751923, -1.1711266 ],
       [-0.09950493,  0.91092163]])

In [25]:
np.random.randint(1,100)

85

In [26]:
np.random.randint(1,100,10)

array([ 3,  8, 15, 70, 46, 62, 99, 77, 61, 41])

# METHODS

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr = np.random.randint(0,50,10)

In [30]:
ranarr

array([ 6, 41,  5,  1, 40,  4, 38, 14, 35, 30])

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
ranarr.max()

41

In [35]:
ranarr.min()

1

In [37]:
ranarr.argmax()

1

In [41]:
ranarr.argmin()

3

In [44]:
ranarr.shape

(10,)

In [45]:
ranarr.dtype

dtype('int32')

# NUMPY INDEXING AND SELECTION

In [46]:
import numpy as np

In [47]:
arr = np.linspace(1,50,10)

In [48]:
arr

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [49]:
arr[0]

1.0

In [50]:
arr[0:5]

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778])

In [51]:
arr[5:]

array([28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

## slicing

In [60]:
slice_of_arr = arr[:6]

In [61]:
slice_of_arr[:] = 99

In [62]:
slice_of_arr

array([99., 99., 99., 99., 99., 99.])

In [63]:
arr

array([99.        , 99.        , 99.        , 99.        , 99.        ,
       99.        , 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [64]:
arr_copy = arr.copy()

In [65]:
arr_copy

array([99.        , 99.        , 99.        , 99.        , 99.        ,
       99.        , 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [66]:
arr_copy[:] = 100

In [67]:
arr_copy

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100.])

In [68]:
arr

array([99.        , 99.        , 99.        , 99.        , 99.        ,
       99.        , 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [72]:
my_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [73]:
my_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
my_arr[0][2]

3

In [76]:
my_arr[1, 2]

6

In [77]:
my_arr[:2, 1:]

array([[2, 3],
       [5, 6]])

In [78]:
arr = np.arange(1,11)

In [79]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
bool_arr = arr > 5

In [82]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [83]:
arr[arr<3]

array([1, 2])

# NUMPY OPERATIONS

## ARRAY WITH ARRAY

In [84]:
import numpy as np

In [85]:
arr = np.arange(0,12)

In [86]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [88]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## ARRAY WITH SCALARS

In [90]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111])

In [91]:
arr /110

array([0.        , 0.00909091, 0.01818182, 0.02727273, 0.03636364,
       0.04545455, 0.05454545, 0.06363636, 0.07272727, 0.08181818,
       0.09090909, 0.1       ])

In [92]:
arr / arr

C:\Users\DELL\AppData\Local\Temp\ipykernel_5232\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [93]:
1 / arr

C:\Users\DELL\AppData\Local\Temp\ipykernel_5232\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909])

In [94]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

## UNIVERSAL ARRAY FUNCTIONS

In [95]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [96]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04])

In [97]:
np.max(arr)

11

In [98]:
arr.max()

11

In [99]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021])

In [100]:
np.log(arr)

C:\Users\DELL\AppData\Local\Temp\ipykernel_5232\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527])

In [104]:
np.sum(arr)

66

In [111]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [107]:
np.random.randint(0,1)

0